ORM: Add Tencent/APIJSON
taosdata/awesome-tdengine pull request #5
Opened 2022-07-19 10:59 UTC by TommyLemon

https://github.com/taosdata/awesome-tdengine#orm

Commit: Support TDengine
https://github.com/Tencent/APIJSON/commit/4886ee923659826ff980cbd55ab36e5adf570d63

Demo for TDengine with APIJSON:
https://github.com/APIJSON/APIJSON-Demo/tree/master/TDengine/single
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONBoot-MultiDataSource

2022-07-19 16:26 UTC, arielyang requested changes

2022-07-19 16:26 UTC, arielyang commented on README.md
> +- [APIJSON](https://github.com/Tencent/APIJSON) A JSON Transmission Protocol and an ORM Library for providing APIs and Docs without writing any code.
Please add a dash before description, as others.

2022-07-20 02:01 UTC, TommyLemon commented on README.md
> +- [APIJSON](https://github.com/Tencent/APIJSON) A JSON Transmission Protocol and an ORM Library for providing APIs and Docs without writing any code.
> Please add a dash before description, as others.

What's a dash?

2022-07-20 03:05 UTC, arielyang approved these changes

2022-07-20 03:06 UTC, merged