update  iotsharp.data.taos
taosdata/awesome-tdengine pull request #9
Opened 2022-09-27 10:12 UTC by maikebing

2022-09-30 04:39 UTC, ericyangpan commented on README.md
> +- [IoTSharp](https://github.com/IoTSharp/IoTSharp/blob/master/IoTSharp.Data.TimeSeries/TaosStorage.cs) - IoTSharp is an open-source IoT platform for data collection,.It supports storing time series d
There is a typo after collection

2022-09-30 08:48 UTC, arielyang commented on README.md
> +-
Remove this empty item.

2022-09-30 08:48 UTC, arielyang commented on README.md
> +- [IoTSharp](https://github.com/IoTSharp/IoTSharp/blob/master/IoTSharp.Data.TimeSeries/TaosStorage.cs) - IoTSharp is an open-source IoT platform for data collection,It supports storing time series da
A space followed comma is needed.

2022-09-30 08:50 UTC, arielyang commented on README.md
> +- [IoTSharp.Data.Taos](https://www.nuget.org/packages/IoTSharp.Data.Taos/)  - TDengine's ADO.Net provider. (.Net Framework 4.6+, .Net Standard2.0+,.Net 5.0+)  [more](https://github.com/IoTSharp/Entit
[more] link cannot appear in the description

2022-09-30 08:50 UTC, arielyang commented on README.md
> +- [IoTSharp.Data.Taos](https://www.nuget.org/packages/IoTSharp.Data.Taos/)  - TDengine's ADO.Net provider. (.Net Framework 4.6+, .Net Standard2.0+,.Net 5.0+)  [more](https://github.com/IoTSharp/Entit
.Net or .NET?

2022-09-30 08:54 UTC, arielyang commented on README.md
> +## Health Checks
I don't think `Health Checks` can be an independent category now. You can place it in `Others` section till there are more content under `Health Checks`.

2022-09-30 08:55 UTC, arielyang requested changes
See the single comments.

2022-10-31 04:47 UTC, maikebing commented
合并？

2022-10-31 15:49 UTC, merged